### ISSUE TITLE
Geometry: Implement 'triangle'

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#120]
Today, we don't have a simple way to create a `Triangle` primitive to use in rendering the UI.

We should create a wrapper similiar to the `Quad` primitive: https://github.com/bryphe/revery/blob/master/src/Geometry/Quad.re

...but for creating Triangles. This is important for implementing border-styling in #119

**Comment by Akin909** [comment]
I think this was done in #123 but the issue didn't close so closing cc @bryphe @OhadRau (in case I'm wrong)
