### ISSUE TITLE
Documentation: Integrate odoc to generate documentation

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#122]
[`odoc`](https://github.com/ocaml/odoc) is a great OCaml-community-supported project for generating documentation - and it even integrates with `esy`. It'd be awesome if we could use it to generate some initial documentation.

I imagine we'll need to do a better job of documenting in the files (using the proper code-block comments to get good descriptions in the documentations) - it'd be helpful to know what we need to do there to get high-quality docs.

**Comment by ulrikstrid** [comment]
cc @ostera

**Comment by Akin909** [comment]
@Samatar26 (@bryphe, @Samatar26 is a friend who is interested in helping out, he's a JS developer, new to reason), this might be a good issue for you to start with if you want to help out, might need to have a look at the docs for `odoc` and see how to integrate it here then maybe find some comments and change them to the right ones (its in the docs) and see if you can output some docs

**Comment by wokalski** [comment]
We've been also trying to research this for Brisk. It'd be great to use the same infra.

**Comment by ulrikstrid** [comment]
The  infra is actually done in #251, when we land #272 with some actual docs I think this can be closed

**Comment by bryphe** [comment]
We actually have some basic docs now: https://www.outrunlabs.com/revery/api/revery/
