### ISSUE TITLE
Bug: Border does not render if background is transparent

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#145]
__Issue:__ If a `border` is specified, but no `background`, the border does not render.

For example, for this component:
```
module Test = (
  val component((render, ~children, ()) =>
        render(
          () => {
            let borderStyle =
              Style.make(
                ~border=Style.Border.make(~width=10, ~color=Colors.white, ()),
                (),
              );

            let innerStyle =
                Style.make(
                    ~backgroundColor=Colors.red,
                    ~width=100,
                    ~height=100,
                    (),
                );

              <view style=borderStyle>
                  <view style=innerStyle />
              </view>
          },
          ~children,
        )
      )
);
```

I would expect to see this:
![image](https://user-images.githubusercontent.com/13532591/50378853-6bc6ee80-05f0-11e9-8565-a671224d3a9e.png)

But get: 
![image](https://user-images.githubusercontent.com/13532591/50378860-88632680-05f0-11e9-8ead-a9df77f60e60.png)

I actually hit this in #138 , which is why I added a pretty transparent background here:
https://github.com/bryphe/revery/blob/d05c343e67c90b81fdc19da74fbf59b5e6a87536/examples/Bin.re#L113

The issue seems to be this check: https://github.com/bryphe/revery/blob/d05c343e67c90b81fdc19da74fbf59b5e6a87536/src/UI/ViewNode.re#L241

**Comment by OhadRau** [comment]
Whoops, I think in my head I was looking at that `c.a` as `style.opacity` when I went back to check that code. I'll fix this real quick

**Comment by bryphe** [comment]
Fixed by #147 - thanks @OhadRau !

**Comment by OhadRau** [comment]
I think this snuck back in when the box-shadows were merged...

**Comment by bryphe** [comment]
Ah, bummer - thanks for catching it @OhadRau . I'll reopen to track.

Also trying to think about ways to catch these sorts of regressions via CI - put some thoughts in #156
