### ISSUE TITLE
Examples: Consolidate to a single example

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#158]
Now that we have `Clickable` and `<Button />` in #152 , I was thinking it'd make sense to consolidate to a single example project. We could still keep each sample in its own Module - but have some sort of navigation story to go between them. 

For example, we could have `<Button />` for each example on a pane, and then render the selected example in the remaining space.

It'd be nice to just be able to run `esy x Examples.exe` and be able to quickly navigate between them!

**Comment by bryphe** [comment]
I'll give this a go this week!

**Comment by tcoopman** [comment]
I guess this is fixed?

**Comment by bryphe** [comment]
Thanks @tcoopman , good catch! Yes, fixed with #201
