### ISSUE TITLE
Examples: Publish our WebGL examples

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#159]
Now that we have text rendering in WebGL (thanks @jchavarri !), I'm thinking it makes sense to publish our WebGL examples to a website - either GH pages or using netlify or something. It'd be a really easy way for people to try things out without needing to set up to start.

**Comment by OhadRau** [comment]
Was just thinking this last night! If we get a logo & what not together we can just make an official website for this. Also, would be great if we could integrate the Reason compiler to have an interactive demo/tutorial there (not sure how feasible that is)

**Comment by bryphe** [comment]
Yes, this would be great!

I love the idea of an interactive demo/tutorial. Seems totally doable, @thangngoc89 has done some incredible work on Sketch: https://github.com/Sketch-sh/sketch-sh that shows how to evaluate JSOO in the browser. He also has a great series of blog posts on his development: https://khoanguyen.me/

In addition, he pointed me to the JSOO examples: http://ocsigen.org/js_of_ocaml/3.1.0/manual/files/toplevel/index.html - great demonstration that it is feasible!

I could see this happening incrementally, in 3 stages:
1) Publish the JS-compiled WebGL apps standalone
2) Publish them in a way where we can have the source-code read-only next to the examples (for example, would be nice to have it set up so that, with #158 , when you switch examples - we switch to the correct source code)
3) Publish them in a way where they are editable (perhaps we pre-compile all of Revery in a way that we can integrate with the JSOO top-level, and then expose the individual example modules as something that we can compile in the browser)

But I think this would really get people interested in `revery`. Zero friction to try the examples and experiment with the API!

**Comment by thangngoc89** [comment]
Ping me if you need my helps. all of those should be easy. but 3 would be scary because you won't have any protection against bad code

**Comment by bryphe** [comment]
We have editable samples now at our playground: https://www.outrunlabs.com/revery/playground/ so this is all set 👍

**Comment by rdrey** [comment]
@bryphe I think it would be nice to include a single sample outside of the playground somewhere to see how big/small an optimised revery app can be in the browser. I might have missed that on the site somewhere?

**Comment by trusktr** [comment]
This is interesting! Got a link to a WebGL example?
