### ISSUE TITLE
UI Events: onMouseOver, onMouseOut

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#186]
I'd like to be able to implement 'hover styles' on `<Button />`, `<view />`'s, etc.

Ideally, we could have something like this:
```
        let defaultBackgroundColor = Colors.red;
        let hoverBackgroundColor = Colors.green;
        let (backgroundColor, setBackgroundColor) = useState(defaultBackgroundColor);

        let style = Style.make(~backgroundColor, ..., ());

       <view onMouseOver={() => setBackgroundColor(hoverBackgroundColor)} onMouseOut={() => setBackgroundColor(defaultBackgroundColor)} />
```

This might be a bit verbose, but would allow us to have more convenient wrappers on top of these primitives.

I think the work done by @OhadRau in #168  opens the door for this - we know which element the mouse is over. We could keep track of the 'current' element we are over, and if that changes, dispatch the `onMouseOut` event, and dispatch the `onMouseOver` event to the new element.

To have similiar behavior as the browser - `onMouseOut` and `onMouseOver` would __bubble__ (like @Akin909 's implementation in #173 ). However, there are counterpart events `onMouseLeave` and `onMouseEnter` that _do not_ bubble.

**Comment by samatar26** [comment]
@bryphe Can I have a go at this?

**Comment by bryphe** [comment]
@samatar26 - definitely, that would be great. Thank you for the help!
