### ISSUE TITLE
Fails to 'esy install' on Ubuntu 18.04

### ISSUE THREAD

**Issue by gladimdim** [revery-ui/revery#204]
Esy install fails to complete with such error:
***
/usr/bin/ld: cannot find -lpng
/usr/bin/ld: cannot find -lbz2
***

This can be fixed by 
```sh
sudo apt install libpng-dev
sudo apt install libbz2-dev
```

I had to install these additional packages:

```
sudo apt install m4
```

My environment: 
Linux gladimdim-notebook 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gladimdim** [comment]
Reproduced on Windows WSL:

    

> 
> Using compiler: gcc
>     include...
>     .
>     ..
>     freetype
>     ft2build.h
>     lib..
>     .
>     ..
>     cmake
>     libfreetype.a
>     pkgconfig
**>     /usr/bin/x86_64-linux-gnu-ld: cannot find -lbz2**
>     collect2: error: ld returned 1 exit status
>     ./esy/test.sh: 21: ./esy/test.sh: ./test: not found
>     error: command failed: './esy/test.sh' (exited with 127)
>     esy-build-package: exiting with errors above...

**Comment by bryphe** [comment]
Thanks for adding this to the docs, @gladimdim ! I'll close this out.
