### ISSUE TITLE
Clicks start target and end target should match.

### ISSUE THREAD

**Issue by jordwalke** [revery-ui/revery#227]
In order to detect a click action the start should be required to match the end target. Right now it seems only the end target (mouse up) is listened to.

It would be nice if revery left room for gesture handlers to be built - a click is just a special case of a more complicated gesture system. but even with clicks, you often want very gesture-like cancellation. For example, if you mouse down, and then someone scrolls on the trackpad, the scrolling gesture should be able to prevent the click gesture from being recognized.

**Comment by wokalski** [comment]
cc @ rauanmayemir we talked [about it yesterday](
https://github.com/briskml/brisk/pull/37#issuecomment-455859767). It'd be interesting to have the same API surface (we could have an empty .mli) as a dep to enforce it automatically.

**Comment by bryphe** [comment]
Definitely! We actually have a `TODO` here tracking this:
https://github.com/revery-ui/revery/blob/3e8602acc2992c6e5e5475df0d1e18c7ee2109e3/src/UI_Components/Clickable.re#L29

A couple bugs with the existing logic - if you 'mouse down' on the `<Clickable />`, and move out, it will stay w/ opacity 1.0 (it should not). When the `<Clickable />` component was first implemented, we didn't really have faculty to handle both this case and the 'mouse up' case - but we do now with the `Mouse.setCapture` API.

Improved behavior for `<Clickable />` should be to:
- On `mousedown`, call `Mouse.setCapture`.
- On the captured `mousemove` - check if cursor position is in bounds, and set opacity appropriately.
- On the captured `mouseup` - check if cursor position is in bounds, and only dispatch if it is.

To get the bounds, we'll need to hold a `ref` to the clickable, and use `ref#getBoundingBox` to check if the cursor is inside the bounds. The `<Slider />` example shows something similiar: https://github.com/revery-ui/revery/blob/3e8602acc2992c6e5e5475df0d1e18c7ee2109e3/src/UI_Components/Slider.re#L48

**Comment by jordwalke** [comment]
> It'd be interesting to have the same API surface (we could have an empty .mli as a dep to enforce it automatically.)

Check out Dune's upcoming virtual libraries!
