### ISSUE TITLE
UI - Component: Tree View

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#246]
It'd be helpful to have a default 'tree-view' style component available. 

Some possible API ideas:
- react-treeview: https://github.com/chenglou/react-treeview
- react-ui-tree: https://github.com/pqx/react-ui-tree
- react-treebeard: https://github.com/storybooks/react-treebeard

We could use font-awesome to find some good icons for expand/collapsed state (or even use triangles from the border styling: https://css-tricks.com/snippets/css/css-triangle/)

**Comment by Akin909** [comment]
I'm currently taking a look at this will open a WIP PR once I have something to show :incoming_envelope:
