### ISSUE TITLE
Explain how React gets compiled to native code

### ISSUE THREAD

**Issue by jnak** [revery-ui/revery#258]
The Readme says that:

> Revery is kind of like super-fast, native Electron - with a bundled React, Redux, and a fast build system - all ready to go!

> Your apps are compiled to native code with the Reason / OCaml toolchain - with instant startup and performance comparable to native C code.

Assuming that you are using react-reason bindings to use React from ReasonML, I'm wondering how you compile the app down to native code. I knew it was possible to compile a Reason app with JS bindings down to Javascript, but I didn't know it was possible to compile a ReasonML app that includes JS binding to native code. 

Can you point us at resources that document this? I would love to learn more about it and I'm sure many people are not aware that is actually possible. 

Thanks,
J

**Comment by wokalski** [comment]
Hey @jnak, that's a good question and I think we might need to reword the readme. Revery has really blown up in the recent days. Anyway, Revery is powered by [brisk-reconciler](https://github.com/briskml/brisk-reconciler) which is a react.js like reconciler written in pure OCaml. Please note that the goal of brisk is not 100% feature and semantic parity with React.js but we do want to keep everything similar and easy to learn.

**Comment by OhadRau** [comment]
Ah this is kind of unclear in the README. We have our own "clone" of React and Redux, rather than the real thing. Since all that code is written inside of Reason it's able to compile to native because it doesn't require any JS bindings. Everything implemented as a JS binding is also duplicated as a C/C++ binding for native code.

**Comment by jnak** [comment]
I see. It was too good to be true :)  Thanks for updating the README.
