### ISSUE TITLE
A way to build using OPAM?

### ISSUE THREAD

**Issue by pmetzger** [revery-ui/revery#275]
Is it possible, for people who spend most of their time in the OCaml ecosystem, to have a method to build just using OPAM rather than esy?

**Comment by bryphe** [comment]
Hi @pmetzger - thanks for the issue!

I would love to have a buildable  OPAM package. There's actually already an issue tracking this - #71 . Some related discussion there (at least a brain dump of some things we need...). There are several packages that revery depends on that we'd also need to port to OPAM.

I'll close this as a dup of #71 so we can track the work and discussion there.
