### ISSUE TITLE
A logo for the project

### ISSUE THREAD

**Issue by osenvosem** [revery-ui/revery#277]
Hello. Every good project needs to have a good logo. Let me share a few ideas on that.

The color palette is the same in all cases and based on the Reason logo's red color combined with a well-contrasting color.

### A couple of simple ideas

![simple 1 2x](https://user-images.githubusercontent.com/6762673/51898087-323c8c80-23c1-11e9-90b2-648c2c494e0d.png)
![simple 2 2x](https://user-images.githubusercontent.com/6762673/51898094-35d01380-23c1-11e9-8235-6702efbea66f.png)

### A bit more sophisticated idea

The idea is based on the definition of the word "revery" as a daydream and is expressed through daydreaming eyes. 🙂

![eye 1 2x](https://user-images.githubusercontent.com/6762673/51898473-040b7c80-23c2-11e9-86a8-887cee11c008.png)
![eye 2 2x](https://user-images.githubusercontent.com/6762673/51898486-0d94e480-23c2-11e9-9e99-fcc57ef0e3be.png)
![eye 3 2x](https://user-images.githubusercontent.com/6762673/51898498-12599880-23c2-11e9-8564-38192e3e854c.png)
![eye 4 2x](https://user-images.githubusercontent.com/6762673/51898517-1be30080-23c2-11e9-8056-7307d13234fe.png)

What do you think?

**Comment by bryphe** [comment]
@osenvosem - thank you very much for the ideas! Agree, we definitely need to build up the 'brand'. I like the thought put into the 'daydream' idea. 

@lpalmes has a friend who is also working on some concepts for us. We'll share those out too when they are ready.

**Comment by OhadRau** [comment]
Wow these are awesome. I really like things that make it clear what the project is from the logo alone so I think the "eye" versions would be best (if we do something too similar to the Reason logo people might get confused between the two)

**Comment by lpalmes** [comment]
#289 @nic0lino has been working on this, any comments or feedback will be appreciated it guys 😃
