### ISSUE TITLE
Style is missing flexWrap

### ISSUE THREAD

**Issue by nikgraf** [revery-ui/revery#283]
If I understand correctly you using Yoga under the hood and it already supports flexWrap: https://yogalayout.com/docs/flex-wrap/

Is there a reason why it's not supported or is this an easy addition? Happy to open a PR: https://github.com/revery-ui/revery/blob/master/src/UI/Style.re#L35-L38

**Comment by wokalski** [comment]
Afaik this library depends on Jordan Walke's Flex. https://github.com/jordwalke/flex

**Comment by nikgraf** [comment]
Yeah, he supports it too: https://github.com/jordwalke/flex/blob/12d61f54aca648ecf4c546551964b3c633c7cc9a/src/lib/LayoutTypes.re#L76

**Comment by bryphe** [comment]
Thanks for the issue, @nikgraf !

 Yes, we are still missing some of the style properties supported by the `flex` library - a PR to add `flexWrap` would be great 👍

**Comment by nikgraf** [comment]
@czystyl justed did one here, but you could check if others are missing as well

**Comment by czystyl** [comment]
@bryphe I see that these props are missing from : 

- [ ] marginStart
- [ ] marginEnd
- [ ] minWidth
- [ ] minHeight
- [ ] maxWidth
- [ ] maxHeight

I don't know the codebase well but couldn't find these options in the codebase. Let me know if Revery should handle that case as well.

**Comment by bryphe** [comment]
@czystyl - good catch! Yes, the `flex` library we're using supports those - we should expose those too in our style props and pass them through for the layout engine. Would be great to have those as well. 👍
