### ISSUE TITLE
Logo project development

### ISSUE THREAD

**Issue by nic0lino** [revery-ui/revery#289]
### Hi everybody! 

My name is Nicolas, I am a Graphic Designer from Argentina and I was invited by @bryphe and @lpalmes to look out proposals for Revery, as a brand.

First of all, I started to go deep on the concepts of the project. _(I'm not really a programmer, so all the perspective I can have about the features of the project its all processed by my knowledge as a communicator haha)_

Chatting with the guys about the origin of the name "revery" and getting deep on the content of the revery general entry. I have found some interesting ideas. 

Bryphe told me that the "revery" name comes from the notion of daydream, a condition where the human gets lost in his own thoughts. And bryphe told me too, that the sort of things that could be represented, could be **the fast**, **the light**, **the platform** and the **modern**

So I picked too, the main description of the project.
![image](https://user-images.githubusercontent.com/39470421/52000804-c0d20c00-249c-11e9-867e-030044d61fab.png)

so then, I started to work first on those concepts, drawing forms and combining them to look forward to a "generatrix", a general scheme that could help me to build a proposal

![image](https://user-images.githubusercontent.com/39470421/52001465-3f7b7900-249e-11e9-87fc-b701e9b5a9f2.png)

I started to find some particular forms in the negative space, with the "bolt", and a maybe overused image but an image that can serve in the building of a "fast building, multiplatform tool"

![image](https://user-images.githubusercontent.com/39470421/52001562-7c477000-249e-11e9-8dbd-28876f1f7490.png)
so, there **the first proposal**

next, I started to build another idea, one based on the old concept of the cloud like a reference of the daydreaming

![image](https://user-images.githubusercontent.com/39470421/52001141-7d2bd200-249d-11e9-98bd-0723ac754634.png)

So I started to work in with some other formal references like the cinetic experiments of the cinetic art, that some artists like [Julio le parc done in Argentina](https://www.google.com/search?biw=1680&bih=940&tbm=isch&sa=1&ei=juRRXP6GHtKZ5gKL57qAAQ&q=julio+le+parc+arte&oq=julio+le+parc+arte&gs_l=img.3..0j0i30j0i8i30j0i24l3.341.856..1176...0.0..0.425.425.4-1......1....1..gws-wiz-img.nsfScQnDnRE). Just to keep and reinforce the "Fast building" idea

![image](https://user-images.githubusercontent.com/39470421/52001910-57073180-249f-11e9-8769-a197380a7c55.png)

So there, i encountered this option

![image](https://user-images.githubusercontent.com/39470421/52001926-61c1c680-249f-11e9-8235-97cacab2fcbf.png)
And there were **the second proposal** _(not my favorite, looks like a bit like a cloud service logo, but I could work too)_
 
and finally, with a @lpalmes joke about being trending on Twitter, I developed a third option, 
that interestingly can be useful to communicate a "fast building, multiplatform library"
![image](https://user-images.githubusercontent.com/39470421/52002440-c7fb1900-24a0-11e9-9ce3-02d96f912799.png)
and there, **the third proposal** *ta da!*

So the final stage looked like this 
![image](https://user-images.githubusercontent.com/39470421/52002577-288a5600-24a1-11e9-82ab-737e10d615ed.png)

Anyway, it's important to clarify these are just, advanced sketches of the proposal. I mean, these options yet need to be re-grided, geometrically and optically adjusted. The options, just "represent" the final form of the logos. 

The guys agreed that the third option was the best one so, with some corrections I started to do that boring part of the gride and I got this.

![image](https://user-images.githubusercontent.com/39470421/52002872-d6960000-24a1-11e9-9b79-3684d832cfa2.png)
_(windows 98 music playing in the background)_

Here is a design chart where you can see how I did the boring part.

![image](https://user-images.githubusercontent.com/39470421/52003008-1f4db900-24a2-11e9-8498-a932f43a2292.png)

You should know, that this is on current developing and that the third proposal its the favorite one (the windows98 one) is the most defined proposal, does not mean that it is the final logo of the project, in fact, I am developing the fourth one so **this is not over.**

_pd: this is my first post on GitHub and I really don't know what I'm doing_

**Comment by wokalski** [comment]
Wow, this is amazing.

**Comment by nic0lino** [comment]
haha thanks! this is just a normal way to do sketches for branding

and i almost forget it. I did some previously research before picking the type.
![image](https://user-images.githubusercontent.com/39470421/52008393-4a8ad500-24af-11e9-8836-c3030eebe5ed.png)

we agreed that [Archivo](https://fonts.google.com/specimen/Archivo?selection.family=Archivo) its the best option

**Comment by OhadRau** [comment]
Just to give a little input -- I really like how the lightning bolt logo stands out even without color. The color scheme also rocks. Thanks for this Nicolas!

**Comment by bryphe** [comment]
Thanks all for the ideas, feedback, and proposals! We have a set of logos now - and I opened #362 to track additional iterations / ideas 👍 Will close this out now but feel free to continue discussion over on #362
