### ISSUE TITLE
Text Rendering: Font baseline is off with letters that go below the baseline

### ISSUE THREAD

**Issue by lessp** [revery-ui/revery#301]
**Issue:**

When characters go below the baseline, they do not line up correctly. (see the big H in the image below)

This is three different `Text`-components, but they're all same size in a container with
```ocaml
alignItems(`Center)
```

when the small `g` is rendered, the baseline seems to change.

![image 2](https://user-images.githubusercontent.com/17602389/52167256-bfad1300-2718-11e9-8f24-0f869614adf1.png)

**Expected behaviour:**

In this example the `H` should line up with the top of the other uppercase letters.

**Environment:**

macOS Mojave 10.14.2

**Comment by bryphe** [comment]
Nice catch, definitely a bug with the text layout.

I'm curious if this reproduces in our JS+WebGL builds too, or if it is specific to native.

**Comment by lessp** [comment]
If I understand you correctly running the JS-version does yield the same result! 🙂 

![font-rendering-baseline](https://user-images.githubusercontent.com/17602389/52369821-c78af100-2a51-11e9-9d19-a1aa112481f5.gif)
