### ISSUE TITLE
How to access state in an event handler

### ISSUE THREAD

**Issue by faisalil** [revery-ui/revery#305]
Hello everyone, 

While trying to look at an issue in the Input.re, I saw that the current way of accessing state in an event handler doesn't work. Here is how it is currently done: 

>     

     let ({isFocused, placeholder, value}, dispatch, slots) =
      React.Hooks.reducer(~initialState={value, placeholder, isFocused: false}, reducer, slots);

    let slots =
      React.Hooks.effect(
        OnMount,
        () =>
          {
            Some(
            Event.subscribe(
              window.onKeyPress,
              event => {
                print_endline("onPress      " ++ event.character);
                dispatch(UpdateText(event.character));

                print_endline("event fired with" ++ value);
                print_endline(
                  "focus " ++ (isFocused ? "true" : "false"),
                );

                onChange(~value=value);
              },
            ),
          )},
        slots,
      );

So inside the event handler hook, if you are accessing state (isFocused), it is the wrong value (looks like it captures the value when calling Event.subscribe.

Looking in reason-react documentation, I saw that they use, [self.handle](https://reasonml.github.io/reason-react/docs/en/callback-handlers). However, looking at revery and brisk code, I couldn't see the concept of self. What is the suggested way to handle this? 

The issue I was trying to fix is that the onChange method of the Input element doesn't really work.

**Comment by bryphe** [comment]
Thanks for the issue / question @faisalil ! Just porting over some discussion from the Discord in case others are curious.

The issue with this is that the `value` is captured in the closure, and that function is kept only once - `OnMount` - so it'll be stale if the value updates and a handler is called later.

This is actually a general issue with React JS hooks too - there's a detailed explanation on the hooks page: https://reactjs.org/docs/hooks-effect.html#detailed-explanation

Usually, you want to use `Always` or `If` (`Always` is actually the default with ReactJS hooks, for this reason!)

**Comment by Akin909** [comment]
do we have a solution for this @faisalil @bryphe? (random issue housekeeping :smile:)

**Comment by Et7f3** [comment]
Any update ?
