### ISSUE TITLE
Playground: Live-editing code

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#319]
Today, our [playground](https://www.outrunlabs.com/revery/playground/) is static - the code shown alongside the examples is _read-only_. This is unfortunate, because it is so tempting to edit it!

@thangngoc89 showed the Reason world how this works with [sketch.sh](https://sketch.sh/)- based off the incredible work on the `js_of_ocaml` toplevel - a demo of it in action here: http://ocsigen.org/js_of_ocaml/toplevel.html#version=4.06.0

It seems like we'll need to expose an entry point for the playground with [`JsooTop`](https://github.com/ocsigen/js_of_ocaml/blob/c2a5c19163b757153ec5d408af773789fca022cb/toplevel/lib/jsooTop.mli) provided by the `js_of_ocaml-toplevel` package. 

Each example is a module that provides a `render: unit => component` function. We'd need to figure out how to execute that 'function' in the context of the top-level, and wire up the example to read from it.

One concern is that it is easy to write code like `while(true) { ... }` that could halt / stop the browser. `sketch.sh` sandboxes this by running the code in a worker, but unfortunately I don't think that is (trivially) workable for us. Perhaps there is a way we could extract that `render` function to a worker?

Some additional links I found interesting while learning / pursuing this space:
- Documentation for Jsoo top level: https://ocsigen.org/js_of_ocaml/3.1.0/api/JsooTop
- @thangngoc89 's sketch blog posts:
   - [Part 1: Introduction](https://khoanguyen.me/sketch/)
   - [Part 2: The Engine](https://khoanguyen.me/sketch/part-2-the-engine/)

@thangngoc89 's posts are a must read - they go over other critical pieces, like how to interpret errors, how to support ReasonML syntax, etc.

Some other items to think about:
- We'll need to 'invert' the flow for running the examples. Right now, we compile the examples and run them - but in this new model - we wouldn't need to 'pre-compile' the examples - we'd compile them in the browser and dynamically call that `render` method some way .
- We'll need to figure out how to handle errors. If we can get line numbers - the monaco editor supports error decorations that can be helpful.
- We'll need to update our Monaco editor initialization logic here: https://github.com/revery-ui/revery/blob/7ff96ebab393c1d76f7cbda4d82900c8a7bb0ace/playground/src/index.html#L76 so that it isn't read-only, and that we respond to code changes.

Build instructions for the playground are available here: https://github.com/revery-ui/revery/tree/master/playground

**Comment by nik72619c** [comment]
Can I add a pr if this change has to be done?

**Comment by bryphe** [comment]
Hi @nik72619c ! A PR for this would be very welcome 👍

**Comment by nik72619c** [comment]
Cool...would just set this flag mentioned

**Comment by nik72619c** [comment]
Filed the PR @bryphe kindly check !

**Comment by thangngoc89** [comment]
@nik72619c Curios. That PR makes things more confusing :)

**Comment by bryphe** [comment]
This work has been moved here: https://github.com/revery-ui/revery-playground

And the latest playground (now with editable code!) is here:
https://www.outrunlabs.com/revery/playground
