### ISSUE TITLE
UI - Input: Cursor has wrong hight

### ISSUE THREAD

**Issue by tcoopman** [revery-ui/revery#321]
As you can see on the screenshot, the custom input (on linux) has a cursor input that's too high. 

![2019-02-09-141351_529x482](https://user-images.githubusercontent.com/45546/52521286-23818f80-2c75-11e9-8b63-ac8eccbd747a.png)

This is only for:
1. the custom input
2. when the cursor is at the start, as soon as you type something, the cursor jumps to the middle of the box.

**Comment by iwilsonq** [comment]
It seems that when setting the custom input examples style prop, it overwrites the `defaultStyles` in the input component that give the cursor that position. Adding height(50) to the custom input styles list gives it the same initial cursor height as the default input.

I think unless a different height is explicitly passed, the default 50px should be used, what do you think?

**Comment by tatchi** [comment]
@bryphe isn't it fixed now?

**Comment by bryphe** [comment]
Thanks @tatchi - yes, looks like it 👍 Will close out.
