### ISSUE TITLE
Font Loading - Native: Discovery of system fonts

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#335]
A significant limitation of Revery today is that you must bundle your own `.ttf` files to get started using it. We do [bundle some fonts](https://github.com/revery-ui/revery-quick-start/tree/master/assets) with Revery and our quick-start, but a better option would be to behave like other apps and allow you to specify a string for a font-family.

Then, we should be able to query installed fonts on the system, and get a font file path from that.

This is proposing adding a __font discovery API__ to our `Native` module, like:
- `getMatchingFontFiles = (fontFamily: string, bold: bool, italic: bool) => string[]`, where the returned string[] is an array of font files (ie, `.ttf`) that match the criteria.

Per-platform implementation:
- __Web__ - I don't think this is doable. We'd just need to throw
- __Windows__ - There is an example of enumerating fonts here: https://docs.microsoft.com/en-us/windows/desktop/gdi/enumerating-the-installed-fonts
- __OSX__ - Is it possible to use `UIFont` familyNames for this? Or potentially a solution like this [StackOverflow](https://stackoverflow.com/questions/19993428/is-it-possible-to-find-the-filepath-of-a-font-used-in-an-mac-osx-app) post?
- __Linux__ - ??

As a stub, for unimplemented platforms could simply return an empty array `[]`, and consumers should expect an empty array if no paths were discovered matching the criteria.

**Comment by tcoopman** [comment]
Found this js library that provides similar functionality crossplatform: https://github.com/foliojs/font-manager

On linux it's using https://www.freedesktop.org/software/fontconfig/fontconfig-user.html.
It seems chromium and electron are both using fontconfig.

**Comment by bryphe** [comment]
Nice find @tcoopman ! fontconfig looks promising 👍

**Comment by Akin909** [comment]
@bryphe could we just borrow chunks of the `c++` logic in `fontconfig` since it does almost exactly what we need but targets js?

**Comment by bryphe** [comment]
Example of using font configs API: <https://gist.github.com/CallumDev/7c66b3f9cf7a876ef75f>

**Comment by bryphe** [comment]
This is implemented now via the `Font.Discovery` API
