### ISSUE TITLE
Regression on scroll bounce after immutable hooks change in brisk-reconciler

### ISSUE THREAD

**Issue by jchavarri** [revery-ui/revery#346]
The scroll bouncing effect is broken in `master`. The underlying cause I believe is the same as https://github.com/revery-ui/revery/issues/342. 

There is an animation for the scroll bouncing where a callback is passed that updates the scroll top position with every new value:

https://github.com/revery-ui/revery/blob/e14abb351c6a7b79659ce50fc3b41cb8af709718/src/UI_Components/ScrollView.re#L165

This model, which assumes that the updater reference stays constant, doesn't work anymore with immutable hooks, because for every new value the updater function `setScrollTop` will be "obsolete", and it will update a memory position that is not the right one anymore.

I tried to use the effects like in #343, but I'm not sure how it should be implemented. @wokalski @bryphe Do you have any hints on how this could be solved? It feels to me like the immutable hooks in brisk-reconciler introduce a quite important divergence in the way React hooks work that could make quite a lot existing patterns and idioms obsolete. What are your thoughts about this?

**Comment by wokalski** [comment]
I've thought about it for a while. Component is a declarative description of the UI and its transitions. With the immutable hook model we capture all state transitions inside the render function which seems  like a very powerful constraint. Race conditions almost disappear.

That said, it might prove to be cumbersome. In the case above, we'd need some adjustments but in general it seems beneficial - for instance in the example above the natural implementation allows for an interruptible animation - the race condition of touch/mouse events and the animation chain is natural to handle if all state transitions have to be explicitly captured in render.

That said, here's a counterexample:

```reason
let counterButtons = (~children as _, ()) => {
  let component = JsooReact.component("CounterButtons");
  component(hooks => {
    let (count, setCount, hooks) =
      JsooReact.Hooks.state(0, hooks);
    (
      hooks,
      <view>
        <button title="Decrement" onPress={() => setCount(count - 1)} />
        <text text={"Counter: " ++ str(count)} />
        <button
          title="Reset (Race condition)"
          onPress={() =>
            ignore(Js_of_ocaml.Dom_html.setTimeout(() => setCount(0), 3000.))
          }
        />
        <button title="Increment" onPress={() => setCount(count + 1)} />
      </view>,
    );
  });
};
```

If we click the reset button first and then click any other button before the three seconds pass, the state update will be lost. I'm wondering if it's possible to nicely handle such cases using the no-stale-update hook model. Another possibility would be just sticking to the current implementation where stale updates are allowed for `Hooks.reducer`. Reducers are built with race conditions in mind which is nice. That said, I am still going to explore the immutable hook model a little bit tomorrow. If I don't find any simple solution for the case above, we should simply refactor such cases to `Hooks.reducer`. What do you think?

**Comment by wokalski** [comment]
Another way to make it explicit in such cases would be:

```
let action = RemoteAction.create();

let counterButtons = (~children as _, ()) => {
  let component = JsooReact.component("CounterButtons");
  component(hooks => {
    let (count, setCount, hooks) =
      JsooReact.Hooks.state(0, hooks);
    let hooks =
      JsooReact.Hooks.subscribe(~handler=setCount, action, hooks);
    (
      hooks,
      <view>
        <button title="Decrement" onPress={() => setCount(count - 1)} />
        <text text={"Counter: " ++ str(count)} />
        <button
          title="Reset (No race condition)"
          onPress={() =>
            ignore(Js_of_ocaml.Dom_html.setTimeout(() => RemoteAction.send(0, action), 3000.))
          }
        />
        <button title="Increment" onPress={() => setCount(count + 1)} />
      </view>,
    );
  });
};
```

It introduces a new `subscription` hook (which would basically be composed out of `useLayoutEffect`.) It's explicit that the action can come at any time and we still have the property that only one state write is possible between renders.

**Comment by wokalski** [comment]
After further consideration I think the current implementation is optimal. Users should use reducers when actions can be dispatched at any time (i.e. stale `dispatch` is allowed) & handle the race conditions there. If someone wants to use `Hooks.state` for the simple case, it should not be allowed to use a stale setter. It just asks for race conditions and is a common source of bugs in React.js.

**Comment by bryphe** [comment]
Thanks for thinking about this, @wokalski ! Sorry for the slow reply on my end.

> Users should use reducers when actions can be dispatched at any time (i.e. stale `dispatch` is allowed) & handle the race conditions there.

This makes sense to me from a 'purity' standpoint - but the concern I have is that this diverges from the way ReactJS behaves. For example in this sandbox: https://codesandbox.io/s/2190jjw6op

If you click `get count with timeout`, which triggers a timeout with a _stale_ `setTimeoutCount`, and then click the `Count` button a bunch of times to trigger intermediate re-renders - the UI will still be updated with the `setTimeoutCount` even though `setTimeoutCount` is from a previous render.

My worry is that developers coming from React won't understand this difference and consider this behavior a bug. 

> If someone wants to use `Hooks.state` for the simple case, it should not be allowed to use a stale setter. It just asks for race conditions and is a common source of bugs in React.js.

I wish there was a way we could detect this at compile-time and yell at the user - so they know they are going to hit this! The worry I have right now is that the 'silently do nothing' behavior is confusing - is there something we can do to improve the developer experience if someone does do this, accidentally?

My preference would be parity with ReactJS behavior, but otherwise... we should certainly have an exception / warning in this case.

It sounds like the best way to fix this in the short term would be to migrate our `Hooks.state` to `Hooks.reducer`, instead? I can give that a go next week 👍

**Comment by jchavarri** [comment]
Thanks @wokalski and @bryphe!

I proposed a temporary fix for this issue that uses the reducer in https://github.com/revery-ui/revery/pull/363.

> This makes sense to me from a 'purity' standpoint - but the concern I have is that this diverges from the way ReactJS behaves.

> My preference would be parity with ReactJS behavior, but otherwise... we should certainly have an exception / warning in this case.

I 100% agree with @bryphe's point of view. I don't think that the benefits of the current implementation outweighs the cognitive load from React it involves. I also agree that if the final decision is to move on with the current approach, it'd be great to provide exception/warning with good explanations i.e. not only how to fix it / a solution (in this case "use `Hooks.reducer`"), but also try to explain why that's the case.

A good reference is the way how Reason errors are very informative when misusing the spread operator (which is also another large divergence from JS):

> Line 1:10-13 Lists can only have one `...` spread, at the end.
> Explanation: lists are singly-linked list, where a node contains a value and points to the next node. `[a, ...bc]` efficiently creates a new item and links `bc` as its next nodes. `[...bc, a]` would be expensive, as it'd need to traverse `bc` and prepend each item to `a` one by one. We therefore disallow such syntax sugar.
> Solution: directly use `concat` or other List helpers.
