### ISSUE TITLE
Widget: Button

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#37]
Placeholder to track adding a `Button` component. I believe we could have this today with the primitives we provide (a view / image), but we do need mouse support:
https://github.com/bryphe/reason-glfw/pull/28

**Comment by bryphe** [comment]
#126 is a pre-requisite for this working correctly.

**Comment by bryphe** [comment]
We have #126 , and a `<Clickable />` component was added in #138 

The work here would be to add a `<Button />` component in the `UI_Components` project (next to `Clickable.re`), and add some default styling around the `<Clickable />` - maybe a background or border? The default styling for React-Native might give some inspiration here: https://facebook.github.io/react-native/docs/button

**Comment by Akin909** [comment]
@bryphe I can look no this :+1:
