### ISSUE TITLE
Is it possible to run shell commands ?

### ISSUE THREAD

**Issue by dev-drprasad** [revery-ui/revery#378]
since its very new project. i thought github-issues is place to ask for help

I am thinking of building app where user clicks a button to run shell commands and show command `stdout` in the app UI. is it something doable with **revery** ? If its , can you point me to some docs/examples ?

Thanks

**Comment by CrossR** [comment]
Hey!

There is the `Unix` module for Reason that enables some of this : https://reasonml.github.io/api/Unix.html.

There is also `Rench` which is supposed to give a `nodejs` style API for Reason written by @bryphe, that contains `spawn` and `spawnSync`, that would also do what you want I think : https://github.com/bryphe/rench.

You should be able to use `spawnSync` to run a command and have its output appear, or `spawn` to run and interactively write stuff out. Oni2 also uses `Rench` to get the neovim instance up and running to communicate with that : https://github.com/onivim/oni2/blob/master/src/editor/Neovim/NeovimProcess.re

**Comment by dev-drprasad** [comment]
@CrossR Thanks Ryan. That is what i am looking
