### ISSUE TITLE
Checkbox inner state doesn’t update when outer state changed

### ISSUE THREAD

**Issue by alexmironof** [revery-ui/revery#384]
When playing around examples I found strange behavior in Todo example.
1. Add 2 todos
2. Mark one done
3. Switch to only done todos
4. Switch to undone todos 

Result: undone todo marked as done, internal checkbox state doesn’t reflect external change

**Comment by nik72619c** [comment]
Could you specify the file to be seen?

**Comment by alexmironof** [comment]
https://github.com/revery-ui/revery/blob/master/examples/TodoExample.re#L142

Here we set `checked` prop from outside

After filtration as I mentioned above `Checkbox` component doesn’t respect that value and uses internal state instead.

Maybe it doesn’t initialized keeping its previous state

**Comment by alexmironof** [comment]
Also if I add 3 todos and mark as done one of them, this issue doesn't replicates, but once there is equal amount of done and undone todos, issue replicates
