### ISSUE TITLE
UI Styles: Text-overflow: ellipsis +/- clip +/- specifiable character

### ISSUE THREAD

**Issue by Akin909** [revery-ui/revery#389]
Currently we have line wrapping with text that is too long, we should also offer the user the opportunity to have overflowing text cut-off and render an ellipsis at that point similar to [css](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow).

We could go with this as an initial starting point or optionally allow the same variability to specify the character to render for the clipped text

**Comment by romgrk** [comment]
One missing feature in CSS could be added maybe: ellipsis in the middle of text, macOS style. It sometimes offers better information than clipping at the end. (e.g. for filepaths)
