### ISSUE TITLE
UI Text: text background color is drawn over the borders

### ISSUE THREAD

**Issue by romgrk** [revery-ui/revery#391]
![screenshot from 2019-03-07 15-34-19](https://user-images.githubusercontent.com/1423607/53987269-82a8b780-40ee-11e9-94c8-34d2b64b8f51.png)

Background color is drawn over the border. 
Logic should be added to remove left & right border width from the available width.

I'm interested in fixing this one but I'm unsure what would be the source of truth for border width. I see the `Style` type can have many border props: `border`, `borderLeft`, `borderHorizontal`, etc. Should we prioritize from the most specific to the less specific? If `border` is set, will, e.g. `borderLeft` be set to the correct value or should this be handled in the `TextNode` logic?

**Comment by bryphe** [comment]
Thanks for logging this issue, @romgrk !

I think the key issue is that the `renderBorders` method from the `ViewNode`: https://github.com/revery-ui/revery/blob/ab47153e681ece7c5adfdfb0440c5277cce3aabb/src/UI/ViewNode.re#L297 

sends back some context about the offset - it returns a `(minX, minY, maxX, maxY)` to communicate where the `ViewNode` should render its interior.

When we render the `TextNode` - it doesn't take into account any of those values (and just uses the parent transform). I think what would make sense is to calculate the `minX`/`minY` in the same way - but include them when we calculate the parent transforms here: https://github.com/revery-ui/revery/blob/ab47153e681ece7c5adfdfb0440c5277cce3aabb/src/UI/Node.re#L141 

I'm not sure if there is a way we can plumb the border values to the `flex` layout engine, such that `dimensions.left` and `dimensions.top` would include those - or if we'd need to calculate those and add them ourselves.

I hope that gives some ideas, at least!

**Comment by bryphe** [comment]
This shouldn't be an issue anymore, since we no longer render background colors with text nodes.
