### ISSUE TITLE
Example: To-do list

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#42]
A to-do list is the canonical example for UI frameworks, so we should have one here too.

There's a few things we need first:
- Checkbox control
- Mouse input

**Comment by schinns** [comment]
I will start working on this 😄

**Comment by bryphe** [comment]
Sweet, thank you @schinns !

**Comment by bryphe** [comment]
Fixed by #311 - thanks @faisalil !

**Comment by schinns** [comment]
thanks @faisalil !

**Comment by albertorestifo** [comment]
Given that #311 has been merged, can we close this?

**Comment by bryphe** [comment]
Fixed with #311
