### ISSUE TITLE
Can't add Core_kernel library to the project

### ISSUE THREAD

**Issue by hexiangdong2017** [revery-ui/revery#448]
info esy build 0.5.6 (using package.json)
info building @opam/base@opam:v0.12.0@bd6e6655
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/base@opam:v0.12.0
    # esy-build-package: pwd: C:\Users\cloud\.esy\3_\b\opam__s__base-opam__c__v0.12.0-0a378147
    # esy-build-package: running: "dune" "build" "-p" "base" "-j" "4"
    File "_build/default/src/mpopcnt.sexp", line 1, characters 1-11:
    1 | '(-mpopcnt)'
         ^^^^^^^^^^
    Error: too many s-expressions found in input
    error: command failed: "dune" "build" "-p" "base" "-j" "4" (exited with 1)
    esy-build-package: exiting with errors above...

  building @opam/base@opam:v0.12.0
esy: exiting due to errors above

**Comment by hexiangdong2017** [comment]
I have find the resolution in https://github.com/janestreet/core_kernel/issues/91

**Comment by yawaramin** [comment]
@hexiangdong2017 hello, as a general rule, please don't `@` mention someone unless you're already communicating with them. Thanks.
