### ISSUE TITLE
Error: Unbound module Revery.Core

### ISSUE THREAD

**Issue by hexiangdong2017** [revery-ui/revery#449]
info esy build 0.5.6 (using package.json)
      ocamlc .App.eobjs/byte/App.{cmi,cmo,cmt} (exit 2)
(cd _build/default && C:\Users\cloud\.esy\3_\i\ocaml-4.7.1004-d00f8396\bin\ocamlc.opt.exe -w -40 -g -bin-annot -I .App.eobjs/byte -I C:/Users/cloud/.esy/3/i/brisk__s__brisk_reconciler-d916c6a4/lib\brisk-reconciler -I C:/Users/cloud/.esy/3/i/flex-1.2.2-3014ff07/lib\flex -I C:/Users/cloud/.esy/3/i/ocaml-4.7.1004-d00f8396/lib/ocaml\threads -I C:/Users/cloud/.esy/3/i/opam__s__base-opam__c__v0.11.1-7b13fde3/lib\base -I C:/Users/cloud/.esy/3/i/opam__s__base-opam__c__v0.11.1-7b13fde3/lib\base\caml -I C:/Users/cloud/.esy/3/i/opam__s__base-opam__c__v0.11.1-7b13fde3/lib\base\md5 -I C:/Users/cloud/.esy/3/i/opam__s__base-opam__c__v0.11.1-7b13fde3/lib\base\shadow_stdlib -I C:/Users/cloud/.esy/3/i/opam__s__bin__prot-opam__c__v0.11.0-7a9d9ea4/lib\bin_prot -I C:/Users/cloud/.esy/3/i/opam__s__bin__prot-opam__c__v0.11.0-7a9d9ea4/lib\bin_prot\shape -I C:/Users/cloud/.esy/3/i/opam__s__color-opam__c__0.2.0-3b23684d/lib\color -I C:/Users/cloud/.esy/3/i/opam__s__core__kernel-opam__c__v0.11.1-33710b56/lib\core_kernel -I C:/Users/cloud/.esy/3/i/opam__s__core__kernel-opam__c__v0.11.1-33710b56/lib\core_kernel\base_for_tests -I C:/Users/cloud/.esy/3/i/opam__s__fieldslib-opam__c__v0.11.0-f5d5f880/lib\fieldslib -I C:/Users/cloud/.esy/3/i/opam__s__gg-opam__c__0.9.3-d23270d5/lib\gg -I C:/Users/cloud/.esy/3/i/opam__s__jane_street_headers-opam__c__v0.11.0-7c39b6e4/lib\jane-street-headers -I C:/Users/cloud/.esy/3/i/opam__s__lwt-opam__c__4.2.1-ca8fc262/lib\lwt -I C:/Users/cloud/.esy/3/i/opam__s__lwt-opam__c__4.2.1-ca8fc262/lib\lwt\unix -I C:/Users/cloud/.esy/3/i/opam__s__mmap-opam__c__1.1.0-eab0ea14/lib\mmap -I C:/Users/cloud/.esy/3/i/opam__s__ocamlfind-opam__c__1.8.0-b42da40d/lib\bytes -I C:/Users/cloud/.esy/3/i/opam__s__parsexp-opam__c__v0.11.0-fb8b22b8/lib\parsexp -I C:/Users/cloud/.esy/3/i/opam__s__ppx__assert-opam__c__v0.11.0-8980525a/lib\ppx_assert\runtime-lib -I C:/Users/cloud/.esy/3/i/opam__s__ppx__bench-opam__c__v0.11.0-63ec2768/lib\ppx_bench\runtime-lib -I C:/Users/cloud/.esy/3/i/opam__s__ppx__compare-opam__c__v0.11.1-f8b29b6a/lib\ppx_compare\runtime-lib -I C:/Users/cloud/.esy/3/i/opam__s__ppx__expect-opam__c__v0.11.1-10acf264/lib\ppx_expect\collector -I C:/Users/cloud/.esy/3/i/opam__s__ppx__expect-opam__c__v0.11.1-10acf264/lib\ppx_expect\common -I C:/Users/cloud/.esy/3/i/opam__s__ppx__expect-opam__c__v0.11.1-10acf264/lib\ppx_expect\config -I C:/Users/cloud/.esy/3/i/opam__s__ppx__hash-opam__c__v0.11.1-c4e24d34/lib\ppx_hash\runtime-lib -I C:/Users/cloud/.esy/3/i/opam__s__ppx__inline__test-opam__c__v0.11.0-919fd53f/lib\ppx_inline_test\config -I C:/Users/cloud/.esy/3/i/opam__s__ppx__inline__test-opam__c__v0.11.0-919fd53f/lib\ppx_inline_test\runtime-lib -I C:/Users/cloud/.esy/3/i/opam__s__ppx__sexp__conv-opam__c__v0.11.2-91b1ebec/lib\ppx_sexp_conv\runtime-lib -I C:/Users/cloud/.esy/3/i/opam__s__result-opam__c__1.3-97276d6b/lib\result -I C:/Users/cloud/.esy/3/i/opam__s__seq-opam__c__base-2e840844/lib\seq -I C:/Users/cloud/.esy/3/i/opam__s__sexplib-opam__c__v0.11.0-33d346b3/lib\sexplib -I C:/Users/cloud/.esy/3/i/opam__s__sexplib0-opam__c__v0.11.0-0d0abb4b/lib\sexplib0 -I C:/Users/cloud/.esy/3/i/opam__s__splittable__random-opam__c__v0.11.0-67b9fd1f/lib\splittable_random -I C:/Users/cloud/.esy/3/i/opam__s__stdio-opam__c__v0.11.0-f14ee92a/lib\stdio -I C:/Users/cloud/.esy/3/i/opam__s__typerep-opam__c__v0.11.0-11f61d30/lib\typerep -I C:/Users/cloud/.esy/3/i/opam__s__variantslib-opam__c__v0.11.0-d37a44a8/lib\variantslib -I C:/Users/cloud/.esy/3/i/reason_fontkit-2.4.1-51716248/lib\fontkit -I C:/Users/cloud/.esy/3/i/reason_gl_matrix-0.9.9304-b93d8592/lib\reglm -I C:/Users/cloud/.esy/3/i/reason_glfw-3.2.1024-5356750f/lib\reglfw -I C:/Users/cloud/.esy/3/i/reason_native__s__console-0.0.3-4b408091/lib\console\lib -I C:/Users/cloud/.esy/3/i/rebez-fa97c6fe/lib\rebez\lib -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_Core -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_Draw -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_Geometry -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_Math -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_Native -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_Shaders -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_UI -I C:/Users/cloud/.esy/3/i/revery-0.15.4-237b60e1/lib\Revery_UI_Components -no-alias-deps -o .App.eobjs/byte/App.cmo -c -impl App.re.ml)
File "App.re", line 4, characters 5-16:
Error: Unbound module Revery.Core
error: command failed: "refmterr" "dune" "build" "-p" "App" (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1

esy: exiting due to errors above

**Comment by hexiangdong2017** [comment]
@yawaramin @rauanmayemir @jc00ke @tcoopman

**Comment by hexiangdong2017** [comment]
@Et7f3

**Comment by rauanmayemir** [comment]
Afaik, `Revery.Core` is now in `Revery`.

**Comment by hexiangdong2017** [comment]
thank you, the project may need to update the playground.
