### ISSUE TITLE
How can I use the flex value like React.js in Revery UI?

### ISSUE THREAD

**Issue by hexiangdong2017** [revery-ui/revery#450]
In React.js, We can use flex to determine the scaling ratio of components when there is excess space. But there is no flex value in Revery UI. So how can I make it in Revery UI?

**Comment by hexiangdong2017** [comment]
@yawaramin @rauanmayemir @jc00ke @tcoopman

**Comment by hexiangdong2017** [comment]
OK, I have find it. I need to use flexGrow

**Comment by rauanmayemir** [comment]
@hexiangdong2017 There's no need to tag people. For this kind of questions you should join Discord.
