### ISSUE TITLE
Gtk and Qt

### ISSUE THREAD

**Issue by ShalokShalom** [revery-ui/revery#465]
Hi there :)

I see libgtk3 is a requirement for this project. 
Does this mean revery builds Gtk applications?
Since that one is heavily focused on GNOME and Linux, while Qt is centered around true multiplatform support, why is that?

**Comment by OhadRau** [comment]
Currently Revery uses GTK for cross platform dialogs (as a fallback when no native one is available).

**Comment by ShalokShalom** [comment]
Thanks. Wouldnt a cross platform toolkit suitable for a cross platform solution?

I am happy to see that Revery uses its own implementation for all the other stuff. :)
