### ISSUE TITLE
Allow windows to be transparent

### ISSUE THREAD

**Issue by kinglouie** [revery-ui/revery#506]
Since GLFW supports transparent framebuffers and also transparent windows including decorations for some operating systems it would be nice if this feature could be accessible through revery.

See [this](https://www.glfw.org/docs/latest/window_guide.html#GLFW_TRANSPARENT_FRAMEBUFFER_hint) GLFW window hint for the transparent framebuffer and further down on the same page is an explanation how to make the whole window transparent.

**Comment by bryphe** [comment]
Yes, this would be great! We need to upgrade [`esy-glfw`](https://github.com/esy-packages/esy-glfw) to GLFW 3.3 support this (it's currently at 3.2, which doesn't have the transparent windows implemented)

**Comment by zbaylin** [comment]
Since we switched to SDL, I think this is easier. I created a PR (https://github.com/revery-ui/reason-sdl2/pull/28) on `reason-sdl2` to implement on a primitive level, which could then be abstracted into revery.

**Comment by szbergeron** [comment]
I'd be interested in hooking this into KFrameworks on the SDL side of things too at some point, would be cool to have
