### ISSUE TITLE
Build instructions 

### ISSUE THREAD

**Issue by ShalokShalom** [revery-ui/revery#507]
Your build instructions are incomplete: 

Add the necessary steps to get the source file to the installation instructions. 

Otherwise, esy has no idea what to build.

**Comment by bryphe** [comment]
I added the following steps to [Building & Installing](https://github.com/revery-ui/revery/wiki/Building-&-Installing):

```
git clone https://github.com/revery-ui/revery
cd revery
```

Hopefully that helps clarify!

**Comment by bryphe** [comment]
I'll close this out, but feel free to edit the Building & Installing page if you have ideas for clarifying it 👍
