### ISSUE TITLE
Performance - Text Rendering: Use texture atlas for characters

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#53]
Rendering text is currently very expensive in Revery, because it involves lots of context-switches to jump between shaders (this is made even worse by the fact that we currently regenerate textures every frame - but that's a separate issue).

The text rendering could be significantly improved by having a texture atlas that contains all the rendered glyphs - then, we could render a line of text in a single pass (or at least, a more minimal set of passes), as opposed to the situation today - where we always render each quad / texture in a single pass.

There's an excellent TextureAtlas implementation by @cryza in Oni here: https://github.com/onivim/oni/blob/master/browser/src/Renderer/WebGLRenderer/TextRenderer/GlyphAtlas/GlyphAtlas.ts that could be useful here 👍

**Comment by Cryza** [comment]
I've started working on a Reason port of the v1 texture atlas. I'll tell you once I've come up with something reviewable! It will probably require some changes in `reason-fontkit` and `reglfw` as well, though 😅

**Comment by bryphe** [comment]
@Cryza - awesome! Thank you very much for your help with this 💯

**Comment by bryphe** [comment]
> It took me quite some time but I think I now have fiddled around enough in a very diffuse way so that I now have a good understanding of what we can do to get a similar approach working as we had in oni v1.

Awesome! Thanks for the update @Cryza .

> I decided to postpone that to keep this issue focused for now though. Just writing everything into the buffer as a float should be sufficient for now. We might want to revisit this later.

Sounds reasonable to me for now.

> This means for now, we need to decide:

> - Keep one render pass per glyph and stay compatible with IE, Edge and Safari
> - Optimise to one render pass per text node and drop compatibility with IE, Edge and Safari

Thanks for calling out the options here! Given that the first option sounds like it is less effort to implement for now, I'm on-board with that. Getting a 'texture atlas' gives us a big leg-up when we decide to implement more aggressive optimizations, and we can follow up with other approaches.

One thing to note - there is an extension for WebGL 1 for `ANGLE_instanced_arrays`, which I believe would add sufficient instancing support for our scenarios. It seems to be very widely supported according to webgl stats: https://webglstats.com/webgl/extension/ANGLE_instanced_arrays - so that might be a future possibility.  I logged an issue in the reason-glfw repo to pick this up eventually: https://github.com/bryphe/reason-glfw/issues/27

**Comment by bryphe** [comment]
Skia integrated in #567 handles this for us, now!
