### ISSUE TITLE
Broken link in Revery's website

### ISSUE THREAD

**Issue by arnau** [revery-ui/revery#531]
Hi, I found a link to https://www.outrunlabs.com/revery/docs, which is broken for me, in the "Getting Started" section.

**Comment by Et7f3** [comment]
Where have you found this ?

**Comment by arnau** [comment]
The link in "Read the docs".

<img width="913" alt="Screenshot 2019-08-26 at 17 27 41" src="https://user-images.githubusercontent.com/33837/63706286-ed79b680-c826-11e9-8f18-6072f0bf81f9.png">

**Comment by Et7f3** [comment]
I don't see repo for website source. Maybe @bryphe can fix it.

**Comment by bryphe** [comment]
Thanks @arnau and @Et7f3 ! I just deployed a fix for this.
