### ISSUE TITLE
How to build a distributable package for MacOS?

### ISSUE THREAD

**Issue by AllenDang** [revery-ui/revery#535]
How to build a MacOS deliverable app?

For python I could use pyinstaller, for golang I just compile to get an executable.

I'm new to OCaml ecosystem, any tutorial could help me out?

**Comment by bryphe** [comment]
Hi @AllenDang ,

We just ported out some of our packaging scripts from [Onivim 2](https://github.com/onivim/oni2) into a project called [revery-packager](https://github.com/revery-ui/revery-packager).

This lets you package any revery app into a redistributable OSX app (produces a `tar.gz` and a `dmg` today).

[camlsynth](https://github.com/kenwheeler/camlsynth) is a great example -

**Comment by lessp** [comment]
Has been answered, closing!

Use: https://github.com/revery-ui/revery-packager
