### ISSUE TITLE
state of js compilation

### ISSUE THREAD

**Issue by joprice** [revery-ui/revery#56]
The only notes I see concerning web support are an unchecked box for supporting it as a platform, so I'm assuming this is a known issue, but I'm curious what the state of it is. In the build, I see the script 'build:js'. I ran it, then started an http server in `_build/default/examples` and opened index.html. I got the following error:

`Uncaught TypeError: runtime.caml_glfwDefaultWindowHints is not a function`

I checked `_build/default/examples/Bin.bc.js`, and it seems to be defined. 

I'm personally interested in using js_of_ocaml for full stack dev, so very curious about the root cause here and steps to debug and solve.

**Comment by bryphe** [comment]
> I'm personally interested in using js_of_ocaml for full stack dev, so very curious about the root cause here and steps to debug and solve.

Cool, I'm in the same boat 👍 

The core library we use for all of our OpenGL / rendering stuff actually works to be built via `js_of_ocaml` as well - and runnable in the browser: https://github.com/bryphe/reason-glfw 

There is a gap today to get Revery working completely in the browser - the library we use for parsing / rendering font characters only works on native today: https://github.com/bryphe/reason-fontkit/issues/3 - we'll definitely need to fix that.

But it looks like there is a bug there - I think it's a bug with the way we define that stub in `reason-glfw`: https://github.com/bryphe/reason-glfw/blob/master/src/glfw_stubs.js

**Comment by bryphe** [comment]
Worked through a few issues here:
- bryphe/reason-glfw#48 - Fix `caml_glfwDefaultWindowHints`
- bryphe/reason-glfw#49 - Implement JSOO strategy for `glfwSetKeyCallback`
- bryphe/reason-glfw#52 - fix bug with image loading in WebGL

Now we're hitting errors like:
```
Uncaught TypeError: runtime.caml_fk_new_face is not a function
```

This is expected since `reason-fontkit` doesn't support JSOO yet - have https://github.com/bryphe/reason-fontkit#10 tracking. It'd be great to just have a stub implementation there for now!

**Comment by bryphe** [comment]
With the work @jchavarri did to bring `reason-fontkit` over, and the fixes in reason-glfw, I believe the JSOO strategy is completely unblocked now (aside from some bugs). Closing this, but feel free to open new issues tracking particular bugs.
