### ISSUE TITLE
Text wrapping is borked

### ISSUE THREAD

**Issue by glennsl** [revery-ui/revery#617]
There are several issues with the current text wrapping implementation:

- If it can't fit the first word in the max width, it wraps after the first character of the first word
- The character at the wrap point is simply removed, which means in-word characters disappear if the wrap point is in a word.
- Tabs, and probably other white-space characters, seem to not be considered white-space.
- Consecutive and compound white-space is handled poorly

---

*Edit: original title and post:*

Title: Text wrapping drops character where it wraps when forced to break a word

The character is probably thrown away because it's assumed to be white-space, since it's designed to break between words, not _in_ words.

It also doesn't calculate the optimal location to break the word, but instead just breaks after the first character.

![2019-10-24-213616_152x36_scrot](https://user-images.githubusercontent.com/5207036/67520029-5d31e380-f6a8-11e9-9c24-0469916619a4.png)

**Comment by glennsl** [comment]
I've written a few tests for the text wrapping logic and found that there are several other issues with how the current TextWrapping deals with white-space.

Then I ran the same tests on the implementation from #303, which did much better. It also seems significantly simpler and more robust. And while the current implementation would have to be significantly refactored, it seems like the other one could be fixed fairly simply. To some degree that's because the current implementation is more flexible, and there might also be performance considerations that tip the scales the other way, but it seems worth considering a resurrection of #303.

**Comment by glennsl** [comment]
For reference, here's the tests and test results:

### Tests

```rust
  test("single word", ({expect, _}) => {
    expect.string(wrap("test", 3)).toEqual("test");
  });

  test("multiple words", ({expect, _}) => {
    expect.string(wrap("test stuff", 5)).toEqual("test\nstuff");
  });

  test("multiple words - too narrow", ({expect, _}) => {
    expect.string(wrap("test stuff", 3)).toEqual("test\nstuff");
  });

  test("multiple words - tab", ({expect, _}) => {
    expect.string(wrap("test\tstuff", 5)).toEqual("test\nstuff");
  });

  test("multiple words - consecutive white-space", ({expect, _}) => {
    expect.string(wrap("test   stuff", 5)).toEqual("test\nstuff");
  });

  test("multiple words - compund white-space", ({expect, _}) => {
    expect.string(wrap("test \t stuff", 5)).toEqual("test\nstuff");
  });
```

### Current

```rust
  let wrap = (str, len) => {
    let (lines, _) =
      TextWrapping.wrapText(
        ~text=str,
        ~measureWidth=String.length,
        ~maxWidth=len,
        ~wrapHere=TextWrapping.isWhitespaceWrapPoint,
      );

    String.concat("\n", lines);
  };
```

Results:

```
 • TextWrapping › single word

    Expected value to equal:
      "test"
    Received:
      "t
      st"

  • TextWrapping › multiple words - too narrow

    Expected value to equal:
      "test
      stuff"
    Received:
      "t
      st
      stuff"

  • TextWrapping › multiple words - tab

    Expected value to equal:
      "test
      stuff"
    Received:
      "t
      st\tstuff"

  • TextWrapping › multiple words - consecutive white-space

    Expected value to equal:
      "test
      stuff"
    Received:
      "test
       
      stuff"

  • TextWrapping › multiple words - compund white-space

    Expected value to equal:
      "test
      stuff"
    Received:
      "test
      \t
      stuff"

```

### #303 

```rust
  let wrap = (str, len) => TextWrap.wrap(len, String.length, str);
```

Results:
```
  • Experimental TextWrapping › multiple words

    Expected value to equal:
      "test
      stuff"
    Received:
      "test 
      stuff"

  • Experimental TextWrapping › multiple words - too narrow

    Expected value to equal:
      "test
      stuff"
    Received:
      "test
       
      stuff"

  • Experimental TextWrapping › multiple words - tab

    Expected value to equal:
      "test
      stuff"
    Received:
      "test 
      stuff"

  • Experimental TextWrapping › multiple words - consecutive white-space

    Expected value to equal:
      "test
      stuff"
    Received:
      "test 
      stuff"

  • Experimental TextWrapping › multiple words - compund white-space

    Expected value to equal:
      "test
      stuff"
    Received:
      "test 
      stuff"
```

**Comment by OhadRau** [comment]
Started working on making a library for this. It should fix all the issues described here & also handles proportional fonts properly (i.e. doesn't assume that every character has width 1). It still needs a lot of work to handle some edge-cases\*, but it should be ready to go in terms of a drop-in replacement for what we have now. Interested in feedback on it in the mean time.

https://github.com/OhadRau/revery-text-wrap

\* No support for Unicode, ligatures, uses a lot of ad-hoc rules to decide what characters count as whitespace, etc. The hyphenation algorithm that I'm using right now is also very simple so it isn't good at finding the best breakpoint within a word. My goal is to eventually make this library a lot more configurable so the user can define the rules for breakpoints, when to hyphenate, etc. because I'm not sure I really know the "proper" rules for a lot of those things.
