### ISSUE TITLE
RichText model

### ISSUE THREAD

**Issue by glennsl** [revery-ui/revery#654]
It would be useful to have a model that associates text with text style properties, and can associatively combine into a sequence (a semigroup).

This doesn't need to be fancy to begin with, just the properties we have today (fontFamily, fontSize, color) would be useful, and we'd then have a nice base to extend with other properties.

Something like this:

```reason
module RichText : {
  type t;

  let create: (~fontFamily: string, ~fontSize: int, ~color: Color.t, string) => t;
  let (++): (t, t) => t;
  let measure: t => Dimensions.t;
}
```

The data structure could be implemented as a tree:

```reason
type t =
  | Leaf({ fontFamily: string, fontSize: int, color: Color.t, text: string })
  | Node(t, t);
```

And then it would be nice to have a `RichText` component which turned the model into a sequence of `Text` elements with the appropriate styles set.

**Comment by SirFurness** [comment]
I'm a bit confused on how the implementation as a tree would work. Why not just store it as a list, for example?

**Comment by kyldvs** [comment]
One reason is that it would be slow to modify text in the middle or end of a list.

**Comment by SirFurness** [comment]
So is the tree meant to be used as a linked list? `Node(Leaf, Node(Leaf, ...))`

**Comment by Et7f3** [comment]
If you do that then you have a regular list. I.e. Const/Cell version. This type need to be a balanced tree and printed by infix order. And because it is a tree concatenating (++) is fast.

**Comment by Et7f3** [comment]
One example that can be used to explain is [rope](https://en.m.wikipedia.org/wiki/Rope_(data_structure))

**Comment by SirFurness** [comment]
I see, thanks for the explanation! I'll give the implementation a go.

**Comment by glennsl** [comment]
To be more specific, lists are O(1) for prepend and O(n) for append, while a binary tree is O(1) for concatenation in general/ The tree doesn't need to be balanced for efficient concatenation, which makes it very easy to implement as well, but can be made balanced later to make operations such as insertion in the middle and computing the length more efficient.
