### ISSUE TITLE
Extend `esy format` to native stubs

### ISSUE THREAD

**Issue by zbaylin** [revery-ui/revery#694]
A while back I suggested that we add consistent styling to the C/Objective-C native stubs like we already do for Reason/OCaml files.

@bryphe had suggested [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html), which looked good until I realized you have to build the entirety of LLVM and Clang for just that one tool.

I created [esy-astyle](https://github.com/zbaylin/esy-astyle), which is an esy wrapper around the [Artistic Style](http://astyle.sourceforge.net) code formatting tool. This tool is super lightweight (less than 1MB) and is very configurable, so I think it's a good choice to add to revery. I made this library with the intention of it being used in revery, so I have no problem transferring ownership to the revery-ui org.

The question I have for @bryphe, @Et7f3  and others is what specific style we want to go for. The [Artistic Style documentation](http://astyle.sourceforge.net/astyle.html) is very detailed and the tool is configurable, so we can probably achieve any semi-standard formatting.

Once we determine that, I will make a PR to add it into `esy format`

**Comment by zbaylin** [comment]
The more I look into it, I think the style we are closest to in our Reason code at least is [`--style=google`](http://astyle.sourceforge.net/astyle.html#_style=google), with a 2-space indentation.

**Comment by zbaylin** [comment]
Implemented with the merging of #695 .

**Comment by Et7f3** [comment]
Next time in your PR uou can say close #694 and github will close this issue on merge. https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords @zbaylin
