### ISSUE TITLE
OSX - Catalina: Key repeat broken

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#703]
- Operating System: OSX Catalina
- Revery Version: `master` (commit `99441c7`)

The key repeat is broken on OSX Catalina, somewhere between `d2fd73b` and `99441c7`.

__REPRO:__
- Run revery example app (`esy run`)
- Go to input example
- Press and hold `j`

Expected: `j` should repeat and you should end up with `jjjj...` in the input box
Actual: Only one `j` is entered

Interestingly, this does not repro on OSX 10.14.

This is blocking upgrade for Onivim 2: onivim/oni2#1149

**Comment by CrossR** [comment]
Another interesting thing is that it looks like backspace and enter (probably more) do work still, but letters don't.

Ie in that same example, you can hold backspace to delete all of the letters, or in Oni2 holding enter does move the cursor as much as expected.

**Comment by CrossR** [comment]
I first see this behaviour once this PR is merged: https://github.com/revery-ui/revery/pull/672

I expect its something unrelated to actual input, and more something with some macOS specific option (`ApplePressAndHoldEnabled` or something) and hooking up the notifications has tripped that up.

That is further solidified by the fact that if you hold something like `i` you get the accent pop-up menu (in the corner of the window) and that it doesn't exhibit for arrows or backspace/enter.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10038688/71701657-c4fc5d00-2dc2-11ea-8b5c-e8e232982f27.png">

**Comment by glennsl** [comment]
Apparently this is still an issue. Reported on oni2: https://github.com/onivim/oni2/issues/1222

**Comment by CrossR** [comment]
Should be fixed with #716.

**Comment by bryphe** [comment]
Tested on 10.14/Catalina - looks good to me. Thanks @CrossR and @zbaylin !
