### ISSUE TITLE
Clickables cannot be nested

### ISSUE THREAD

**Issue by glennsl** [revery-ui/revery#709]
`Clickable` is currently implemented by capturing the mouse on `mousedown` and then executing `onClick` on `mouseup` if the pointer is still in the elements bounding box at that point. Not a bad approach, in theory, but unfortunately `mousedown` bubbles and the capture API is imperative and exclusive, which means the shallowest clickable is always going to hijack the capture and register the clicks as happening on itself.

There are a few ways I can think of to address this:

1. Fixing the bubbling so it's conditional somehow. There are a few approaches I can think of for doing this as well, all of which are breaking:
  a. Require event handlers to specify in advance whether events should be propagated. There are various ways to do this too, of course, but they basically boil down to the same concept.
  b. Pass a `next` callback to the event handler, along with the event, so events can be bubbled selective, CPS-style.
  c. Require event handlers return a value to indicate whether to bubble.
2. Implement `Clickable` using a local flag that's set on `mousedown` and reset on `mouseout`/`mouseup` instead of using `capture`. These event will still bubble however, generating click events from all clickables in the hierarchy, so I think we'll need a global mutable as well to make it exclusive and prevent that. Pretty nasty, but non-breaking if it works.

I'll try to get option 2 working, but this isn't a long-term solution and we'll need to fix bubbling at some point anyway. so if anyone has ideas, concerns or other comments about the above, now might be a good time to bring them to light :slightly_smiling_face:

**Comment by Et7f3** [comment]
`Addresses` is not a close keyword but 710 is merged so I close it.
