### ISSUE TITLE
[macOS] Linker error with new Skia build

### ISSUE THREAD

**Issue by zbaylin** [revery-ui/revery#742]
- Operating System: macOS 10.15
- Revery Version: #395ed2ed

- Steps to reproduce:
  - Compile revery on macOS 10.15

- Actual Result:
  - The following linking error:
```
Undefined symbols for architecture x86_64:
  "_jpeg_crop_scanline", referenced from:
      SkJpegCodec::onStartScanlineDecode(SkImageInfo const&, SkCodec::Options const&) in libskia.a(jpeg.SkJpegCodec.o)
  "_jpeg_skip_scanlines", referenced from:
      SkJpegCodec::onSkipScanlines(int) in libskia.a(jpeg.SkJpegCodec.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
error: command failed: 'dune' 'build' '-p' 'Revery' '-j4' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
```
- Expected Result:
  - Revery compiles

@bryphe was saying this might be due to something with the `discover.ml` of `reason-harfbuzz`, so that might be a good place to start looking.

**Comment by bryphe** [comment]
This looks to be a conflict with the system installed `libjpeg` vs the one we build with `libjpeg-turbo` (it's picking up the system one, when it should be picking up our built one).

Does the example in `reason-skia`, on the latest `master` build & run for you @zbaylin ?

- esy '@example' install
- esy '@example' run

If that works - it means a dependency that Revery has, but not reason-skia, is somehow picking up the system `libjpeg`. If that doesn't work - means there is a bug in one of the reason-skia deps where we're inadvertently bringing it in.

**Comment by zbaylin** [comment]
@bryphe `esy @example run` fails in the exact same matter as `esy b` on revery, so I think we found the culprit.

Now just to find a fix...

**Comment by bryphe** [comment]
Hmm, one other possibility - this `DYLD_LIBRARY_PATH` looks wrong to me:
https://github.com/revery-ui/libjpeg-turbo/blob/61e031fdd8d621cb183caaea07133bb346310892/package.json#L17

It seems like this: ```
      "DYLD_LIBRARY_PATH": {
        "scope": "global",
        "val": "/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/:#{self.lib}:$DYLD_LIBRARY_PATH"
      },
```
Could be taking from the system-installed version of `libjpeg`, instead of the one being built. Seems like it should just be `#{self.lib : $DYLD_LIBRARY_PATH}`

**Comment by zbaylin** [comment]
`libjpeg-turbo` builds for me. Not sure if that's indicative of anything, but it might help.

**Comment by bryphe** [comment]
> libjpeg-turbo builds for me. Not sure if that's indicative of anything, but it might help.

The build failure is a _linker error_ - so it won't actually present until we go to build an executable and link. In other words - `reason-skia` probably even builds with `esy build` - but once we build the executable (which happens with `esy @example build` in `reason-skia`) - we hit that linker error. In revery - the example app gets built (and linked) with just `esy build`. So unfortunately it doesn't really give us any new info - it could still be that the `DYLD_LIBRARY_PATH` is incorrect, but it doesn't get exercised until its actually linked.

**Comment by bryphe** [comment]
Trying out changing the `DYLD_LIBRARY_PATH` on CI here: https://github.com/revery-ui/reason-skia/pull/34

**Comment by zbaylin** [comment]
@bryphe the `DYLD_LIBRARY_PATH` change still didn't fix it. Sorry that this is so hard to debug!

**Comment by bryphe** [comment]
No worries @zbaylin - thanks for your help! I wish I could repro it on my Mac or CI.

It might be helpful to have the full, verbose build logs for this issue. (IE - add `--verbose` to the dune build command, and set `ESY__LOG=verbose`). Having the full build command that produced that error could be helpful.

**Comment by bryphe** [comment]
Not sure if there is a way to query the linker on OSX and ask where it is finding `-ljpeg` - that could be useful too!

**Comment by zbaylin** [comment]
Here is a dump with both verbosity settings turned on: https://pastebin.com/sm3kxFMz
