### ISSUE TITLE
Quickstart fails `esy install` for v0.30.0

### ISSUE THREAD

**Issue by BlueHotDog** [revery-ui/revery#793]
- Operating System: Osx Catalina
- Revery Version: 0.30.0
- OCaml version: 4.9.0
- Native, Bytecode, or JS build: Native

- Steps to reproduce: Trying to run `esy install` on the quickstart repo after changing to revery 0.30.0 produces the following error:

- Actual Result:
```
error: command failed: 'git' 'ls-remote' 'https://github.com/bryphe/lru%3Alru.opam.git' '2708c70'
stderr:
         fatal: unable to access 'https://github.com/bryphe/lru%3Alru.opam.git/': The requested URL returned error: 400

stdout:

  resolving @opam/lru@github:bryphe/lru%3Alru.opam#2708c70
  resolving revery@0.30.0
esy: exiting due to errors above
```
- Expected Result:
to not error
- Additional Information:

- Search terms used:

**Comment by glennsl** [comment]
Which version fo `esy` do you have? If it's `0.6.2`, could you provide a complete log? Otherwise I'd suggest you try upgrading `esy`.

**Comment by BlueHotDog** [comment]
I'm using `esy 0.6.2` 
```
info install 0.6.2 (using package.json)
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
error: command failed: 'git' 'ls-remote' 'https://github.com/bryphe/lru%3Alru.opam.git' '2708c70'
stderr:
         fatal: unable to access 'https://github.com/bryphe/lru%3Alru.opam.git/': The requested URL returned error: 400

stdout:

  resolving @opam/lru@github:bryphe/lru%3Alru.opam#2708c70
  resolving revery@0.30.0
esy: exiting due to errors above
```

**Comment by glennsl** [comment]
cc @prometheansacrifice Any idea why this might happen?

**Comment by glennsl** [comment]
The offending dependency is:

https://github.com/revery-ui/revery/blob/26b11613d4616bc7ab89841ca42ea5f5d35addd2/package.json#L38

**Comment by lessp** [comment]
I think `opam`-packages needs to be specified in resolutions, for unreleased packages @glennsl.

See: https://esy.sh/docs/en/using-repo-sources-workflow.html#with-opam-packages

**Comment by prometheansacrifice** [comment]
Esy's parser couldn't understand `"github:bryphe/lru:lru.opam#2708c70"`. Changing it to `"bryphe/lru:lru.opam#2708c70"` will get past this issue.

**Comment by glennsl** [comment]
Thanks @prometheansacrifice!

Odd though, since this has worked fine for me, @bryphe and on the CI boxes for the 22 days since it was added.

Also, should this be considered a bug? Or does the `github:` scheme have a very specific meaning? I tend to leave it out because I've never encountered a scenario where it's actually necessary,  but I've always considered `bryphe/lru` a shorthand for `github:bryphe/lru`, and therefore also considered `:lru.opam`  an optional part for both.

**Comment by prometheansacrifice** [comment]
Definitely a bug in esy! Raised an issue https://github.com/esy/esy/issues/1069

> Odd though, since this has worked fine for me, @bryphe and on the CI boxes for the 22 days since it was added.

This is concerning. Hopefully because the resolution went unused for some reason and that esy never had to parse it. Confirming that it never failed until now (preferably with the version of esy where this passes) would be really helpful.

**Comment by glennsl** [comment]
Fix has been merged into master @BlueHotDog. Would you try again?

**Comment by BlueHotDog** [comment]
Hi guys, still an issue:
```
revery-quick-start on  master [!?] is 📦 v1.3.0 via ⬢ v13.7.0 took 21s
➜ esy install
info install 0.6.2 (using package.json)
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
info resolving esy packages: done
info solving esy constraints: done
error: No solution found:

Conflicting constraints:
  revery-quick-start -> revery -> reason-skia -> esy-freetype2 -> esy-cmake@^0.3.2
  revery-quick-start -> revery -> reason-skia -> esy-skia -> esy-libjpeg-turbo ->
  esy-cmake@github:prometheansacrifice/esy-cmake#2a47392def755074afbf63eb794b94135476b1d1


esy: exiting due to errors above
```
my package.json:
```
{
  "name": "revery-quick-start",
  "version": "1.3.0",
  "description": "Revery quickstart",
  "license": "MIT",
  "esy": {
    "build": "refmterr dune build -p App",
    "buildsInSource": "_build",
    "install": [
      "esy-installer App.install"
    ]
  },
  "revery-packager": {
    "bundleName": "ExampleApp",
    "bundleId": "com.example.app",
    "displayName": "Revery Example App",
    "mainExecutable": "App",
    "windows": {
      "packages": ["zip"],
      "iconFile": "assets/icon.ico"
    },
    "darwin": {
      "packages": ["tar", "dmg"],
      "iconFile": "assets/icon.icns"
    },
    "linux": {
      "packages": ["tar", "appimage"]
    }
  },
  "dependencies": {
    "ocaml": "~4.9.0",
    "revery": "github:revery-ui/revery#master"
  },
  "resolutions": {
    "@opam/cmdliner": "1.0.2",
    "pesy": "0.4.1",
    "rebez": "github:jchavarri/rebez#46cbc183",
    "@opam/merlin-extend": "0.4"
  },
  "scripts": {
    "format": "bash -c \"refmt --in-place *.re\"",
    "run": "esy x App"

  },
  "devDependencies": {
    "ocaml": "~4.9.0",
    "@opam/dune": "*",
    "@opam/merlin": "*",
    "esy-macdylibbundler": "*"
  }
}
```

**Comment by glennsl** [comment]
That's more of an issue with `revery-quickstart` being severely outdated I think.  Let me see if I can get it updated.

In the meantime, you could try the dependencies from https://github.com/revery-ui/revery-workshop instead, which should be more up-to-date.

**Comment by glennsl** [comment]
Should be in order now @BlueHotDog
