### ISSUE TITLE
0.31 is broken after breaking change in reason-sdl2

### ISSUE THREAD

**Issue by glennsl** [revery-ui/revery#867]
Because `reason-sdl2` is not pinned to a specific version and does not follow semver with regards to breaking changes because the version is set up to track the version of `sdl2`, Revery 0.31 is now broken.

Given the difficulty of making `reason-sdl2` follow semver properly, we might want to consider specifying a specific version at least for releases.

It would also be nice if another release could be published to have the latest release in working order.

Original report: https://github.com/revery-ui/revery-quick-start/issues/72

**Comment by bryphe** [comment]
Now that we've "monorepo'd" SDL2 here - this sort of version mismatch should no longer be an issue-
