### ISSUE TITLE
menu bar app

### ISSUE THREAD

**Issue by rickiesmooth** [revery-ui/revery#898]
I'm not very familiar with the native MacOS apps, but is it possible to make a menu bar app with revery?

**Comment by lessp** [comment]
Hey @rickiesmooth! 

I think these two issues may be helpful:

**Native Integration: Menu API:**
https://github.com/revery-ui/revery/issues/250

**Native Integration: Tray API:**
https://github.com/revery-ui/revery/issues/322

I'll close this issue in favour of them. 🙂

**Comment by rickiesmooth** [comment]
oops just naively searched for menu bar, thanks!
