### ISSUE TITLE
Rename project to revery-native

### ISSUE THREAD

**Issue by jet8a** [revery-ui/revery#915]
It's impossible now to find something in google. It always supposes that I made a mistake and want to look for a recovery.
So I propose to rename revery to revery-native or something like that.

**Comment by kyldvs** [comment]
Searching "revery" for me it's the first non-definition entry, and "revery reason" makes it the first entry. This doesn't seem like a problem that needs solving by renaming the whole project.

**Comment by jet8a** [comment]
It would help in the future when google indexed the changes

**Comment by bryphe** [comment]
Thanks for the thoughts!

I agree with @kyldvs points - no plans to rename the project at this time.
