### ISSUE TITLE
Update Building & Installing for windows to include VS build tools

### ISSUE THREAD

**Issue by chinwobble** [revery-ui/revery#975]
In order to get started on Revery and run `esy build` on windows you must have Visual Studio 2017 Build Tools or one of the IDE variants. 

The documentation should indicate this by:
https://github.com/revery-ui/revery/wiki/Building-&-Installing

I suggest adding this to the above documentation:
```
Revery depends on esy-skia which requires `Microsoft Visual Studio 2017 VC Tools` . It can be installed through chocolatey by running:

choco install visualstudio2017buildtools visualstudio2017-workload-vctools -y
```

- Link to repro: https://github.com/revery-ui/revery-quick-start

**Comment by CrossR** [comment]
I believe we can just copy what we do in Oni2 and recommend people install the `windows-build-tools` package from NPM, which includes both the build tools and Python.

https://onivim.github.io/docs/for-developers/building#prerequisites
